-- 015_finding_locus_key.sql — lens-independent location identity for the durable
-- cross-lens dedup fold.
--
-- The finding fingerprint is sha256(lens, file, locus): it intentionally includes
-- the lens so two lenses reporting the same defect get distinct fingerprints and
-- the cross-lens collapse is delegated to triage's in-memory clustering. That
-- clustering state is volatile — it is NOT rebuilt from already-persisted
-- findings when an interrupted run replays its pending candidates, so a
-- WAL-replayed candidate whose same-locus, different-lens sibling was persisted
-- by the prior run became a SECOND finding instead of folding in.
--
-- locus_key = sha256(normFile, locus) is the fingerprint inputs MINUS the lens.
-- Indexed so triage can point-look-up a candidate's exact locus. Existing rows
-- default to '' and do not participate until their next upsert recomputes the
-- key (forward-looking).
--
-- bugbot-ezmx.3: the durable cross-lens fold no longer queries this column
-- directly (it widened to store.FindingsByFileWindow's same-file line-window
-- lookup, so a drifted locus_key still folds in) -- but the column and this
-- index are kept: IsSuppressed's legacy fallback and RenameFindingIdentity's
-- rewrite still match/rewrite locus_key by exact value.
ALTER TABLE findings ADD COLUMN locus_key TEXT NOT NULL DEFAULT '';
CREATE INDEX idx_findings_locus_key ON findings(locus_key);
