package repro

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dpoage/bugbot/internal/sandbox"
	"github.com/dpoage/bugbot/internal/store"
	"github.com/dpoage/bugbot/internal/util"
)

// writeArtifacts writes a self-contained repro bundle for a demonstrated bug to
// artifactDir/<finding-id>/ and returns the bundle directory path. The bundle
// contains the injected repro files (at their plan-relative paths), a run.sh
// capturing the command, and a README.md describing the finding and how to run
// it.
//
// On any error the partially-written bundle directory is removed so a failed
// promotion never leaves stale artifacts behind.
func writeArtifacts(artifactDir string, finding store.Finding, plan *Plan, res sandbox.Result) (dir string, err error) {
	id := finding.ID
	if id == "" {
		id = "unknown"
	}
	dir = filepath.Join(artifactDir, id)

	// Start from a clean slate so a re-run overwrites any prior bundle.
	if rmErr := os.RemoveAll(dir); rmErr != nil {
		return "", rmErr
	}
	if mkErr := os.MkdirAll(dir, 0o755); mkErr != nil {
		return "", mkErr
	}
	// Clean up a partial bundle on any later failure.
	defer func() {
		if err != nil {
			_ = os.RemoveAll(dir)
		}
	}()

	if werr := writePlanFiles(dir, plan); werr != nil {
		return "", werr
	}
	if werr := os.WriteFile(filepath.Join(dir, "run.sh"), []byte(runScript(plan)), 0o755); werr != nil {
		return "", werr
	}
	if werr := os.WriteFile(filepath.Join(dir, "README.md"), []byte(readme(finding, plan, res)), 0o644); werr != nil {
		return "", werr
	}
	return dir, nil
}

// writePlanFiles writes each repro file under dir, creating parent directories
// and rejecting paths that escape the bundle.
func writePlanFiles(dir string, plan *Plan) error {
	for rel, content := range plan.Files {
		clean := filepath.Clean(rel)
		if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("repro: unsafe artifact path %q", rel)
		}
		dst := filepath.Join(dir, clean)
		if mkErr := os.MkdirAll(filepath.Dir(dst), 0o755); mkErr != nil {
			return mkErr
		}
		if werr := os.WriteFile(dst, []byte(content), 0o644); werr != nil {
			return werr
		}
	}
	return nil
}

// runScript renders run.sh: a portable shell script that runs the repro
// command from the bundle directory. The command is the same argv the sandbox
// executed.
func runScript(plan *Plan) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by Bugbot. Copy the listed files into the target\n")
	b.WriteString("# repository, then run this command from the repo root.\n")
	b.WriteString("set -euo pipefail\n\n")
	parts := make([]string, len(plan.Cmd))
	for i, p := range plan.Cmd {
		parts[i] = shellQuote(p)
	}
	b.WriteString(strings.Join(parts, " "))
	b.WriteByte('\n')
	return b.String()
}

// shellQuote single-quotes a shell argument when it contains characters that
// the shell would otherwise interpret.
func shellQuote(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\n'\"\\$`*?[]{}()<>|&;#~") {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// readme renders README.md describing the finding, the expected-vs-actual
// failure, and how to run the repro.
func readme(finding store.Finding, plan *Plan, res sandbox.Result) string {
	var b strings.Builder
	title := finding.Title
	if title == "" {
		title = "Reproduction"
	}
	fmt.Fprintf(&b, "# Reproduction: %s\n\n", title)

	if finding.Severity != "" {
		fmt.Fprintf(&b, "- **Severity:** %s\n", finding.Severity)
	}
	if finding.File != "" {
		fmt.Fprintf(&b, "- **Location:** `%s:%d`\n", finding.File, finding.Line)
	}
	if finding.ID != "" {
		fmt.Fprintf(&b, "- **Finding ID:** `%s`\n", finding.ID)
	}
	b.WriteByte('\n')

	if finding.Description != "" {
		b.WriteString("## Description\n\n")
		b.WriteString(finding.Description)
		b.WriteString("\n\n")
	}

	b.WriteString("## Expected vs. actual\n\n")
	if plan.Expect != "" {
		fmt.Fprintf(&b, "**Expected failure:** %s\n\n", plan.Expect)
	}
	fmt.Fprintf(&b, "**Actual:** the repro exited with code %d", res.ExitCode)
	if res.TimedOut {
		b.WriteString(" (timed out)")
	}
	b.WriteString(", demonstrating the bug. The test is written to PASS once the bug is fixed.\n\n")

	b.WriteString("## How to run\n\n")
	b.WriteString("Copy the files below into the target repository (preserving paths), then run:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("./run.sh\n")
	b.WriteString("```\n\n")
	b.WriteString("Or directly:\n\n")
	b.WriteString("```sh\n")
	b.WriteString(strings.Join(plan.Cmd, " "))
	b.WriteString("\n```\n\n")

	b.WriteString("## Repro files\n\n")
	for _, p := range util.SortedKeys(plan.Files) {
		fmt.Fprintf(&b, "- `%s`\n", p)
	}
	b.WriteByte('\n')

	if out := combinedOutput(res); out != "" {
		b.WriteString("## Captured output\n\n")
		b.WriteString("```\n")
		b.WriteString(trunc(out, 4000))
		b.WriteString("\n```\n")
	}
	return b.String()
}


